-- Create project_images table
CREATE TABLE IF NOT EXISTS project_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE NOT NULL,
    url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE project_images ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow public read access"
ON project_images FOR SELECT
USING (true);

CREATE POLICY "Allow authenticated insert access"
ON project_images FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Allow authenticated update access"
ON project_images FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow authenticated delete access"
ON project_images FOR DELETE
TO authenticated
USING (true);

-- Optional: Migrate existing images from projects table if needed
-- This assumes projects.images is a text array or similar. 
-- If you want to migrate, you'd need a PL/pgSQL function, but we'll skip for now as per request to just create the table.
